FROM agrofelis.os:core
MAINTAINER "Konstantinos Papageorgiou"
RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh;\
	bin/arduino-cli core install arduino:avr
Run arduino-cli lib install servo