# agrofelis unificator server - 2023
FROM node:16.17.0-bullseye-slim@sha256:18ae6567b623f8c1caada3fefcc8746f8e84ad5c832abd909e129f6b13df25b4
#FROM node
MAINTAINER "Konstantinos Papageorgiou" kp@eworx.gr
EXPOSE 8080/tcp
EXPOSE 8080/udp